on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

name: Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run lint
