name: Sync labels
on:
  workflow_dispatch:
    inputs:
      sync:
        description: 'Sync Labels'
        required: false
  push:
    branches:
      - master
    paths:
      - .github/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
