on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    name: Test on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn ci
      - run: yarn run bootstrap
      - run: yarn run test
